server:
  port: 5000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chat
    username: ${env.POSTGRES_USERNAME}
    password: ${env.POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  flyway:
    locations: classpath:db/migration
    enabled: true
    baselineOnMigrate: true