server:
  port: 5000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chat
    username: ${env.MYSQL_USERNAME}
    password: ${env.MYSQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
